[package]
name = "pmv-cli"
description = "Command line interface client for PersonalMediaVault"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.3", features = ["derive"] }
hyper = { version = "0.14.26", features = ["full"] }
hyper-multipart-rfc7578 = "0.8.0"
rpassword = "7.2.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["full"] }
url = "2.4.0"
